[package]
name = "errol"
version = "0.1.0"
authors = [
  "William Stewart <zoidbergwill@gmail.com>",
]

[dependencies]
# github-rs = ""
# rocket = ""
# rocket_codegen = ""
# rocket_contrib = ""
actix-web = ""
diesel = { version = "", features = ["postgres"] }
dotenv = ""
# gitlab = ""
# lettre = ""
# lettre_email = ""
# racer = ""
serde = ""
serde_derive = ""
serde_json = ""
serde_yaml = ""
failure = ""
futures = ""
http = ""
# syntect = ""
