[package]
name = "git-multimail-webhook"
version = "0.1.0"
authors = ["William Stewart <zoidbergwill@gmail.com>"]

[dependencies]
serde_json = "1.0"
serde_yaml = "0.8"
gitlab = "0.1103.0"
serde = "1.0.79"
serde_derive = "1.0.79"
rocket = "0.3.17"
rocket_contrib = "0.3.17"
rocket_codegen = "0.3.17"
lettre = "0.8.2"
lettre_email = "0.8.2"
