[package]
name = "errol"
version = "0.1.0"
authors = ["William Stewart <zoidbergwill@gmail.com>"]

[dependencies]
serde_json = "1.0"
serde_yaml = "0.8"
gitlab = "0.1103.0"
serde = "1.0.79"
serde_derive = "1.0.79"
rocket = "0.3.17"
rocket_contrib = "0.3.17"
rocket_codegen = "0.3.17"
lettre = "0.8.2"
lettre_email = "0.8.2"
syntect = "3.0.0"
racer = "2.1.9"
github-rs = "0.6.1"
